import time, os

# Colors
RESET = "\033[0m"

def apply(text, *codes):
    return "".join(codes) + text + RESET

# Text Colors
def black(t): return apply(t, "\033[30m")
def red(t): return apply(t, "\033[31m")
def green(t): return apply(t, "\033[32m")
def yellow(t): return apply(t, "\033[33m")
def white(t): return apply(t, "\033[37m")
def magenta(t): return apply(t, "\033[35m")
def cyan(t): return apply(t, "\033[36m")

def bright_black(t): return apply(t, "\033[90m")
def bright_red(t): return apply(t, "\033[91m")
def bright_yellow(t): return apply(t, "\033[93m")
def bright_green(t): return apply(t, "\033[92m")
def bright_magenta(t): return apply(t, "\033[95m")
def bright_cyan(t): return apply(t, "\033[96m")
def bright_white(t): return apply(t, "\033[97m")

# Styles
def bold(t): return apply(t, "\033[1m")
def italic(t): return apply(t, "\033[3m")
def underline(t): return apply(t, "\033[4m")

# TRY
def tries():
    choice = input(green("\nWould you like to try this yourself?\n|   Y to continue & N to return:   |")).lower()

    if choice != 'y':
        os.system('cls')
        return

    forbidden = ["input(", "import ", "exit(", "quit("]

    while True:
        os.system('cls')
        print(f"\n==================== {bold(bright_yellow('TRY IT YOURSELF'))} ====================")
        time.sleep(0.3)
        print("Type Python code using the concepts you learned.")
        time.sleep(0.3)
        print("Type 'output' at the last line to run your code.")
        time.sleep(0.3)
        print("Type 'return' at the last line to go back.")
        time.sleep(0.3)
        print("\nNOTE:")
        time.sleep(0.3)
        print("- input(), import, exit(), quit() are NOT allowed here.")
        time.sleep(0.3)
        print("=========================================================\n")
        time.sleep(0.3)

        user_lines = []

        while True:
            line = input(green("> "))

            if line.lower() == "return":
                os.system('cls')
                return

            if line.lower() == "output":
                break

            low_line = line.replace(" ", "").lower()
            if any(f in low_line for f in forbidden):
                print(red("This command is not allowed here. Try again."))
                continue

            user_lines.append(line)

        print(f"\n========== {bold(bright_cyan('OUTPUT'))} ==========")
        code = "\n".join(user_lines)

        try:
            exec(code)
            print("\n\n(Your code is working!)")
        except:
            print(red("There was an error in your code. Please try again."))
            print("===============================")
            input(green("\nPress Enter to retry..."))
            continue

        print("===============================")
        again = input(green("\nTry another code? (y/n): ")).lower()
        if again != 'y':
            os.system('cls')
            break

        os.system('cls')
            
# Print Lesson
def prints():
    print(f"\n========== {bold(bright_magenta('PRINT STATEMENTS'))} ==========")
    time.sleep(0.3)
    print("The print() function displays output on the screen like")
    time.sleep(0.3)
    print("text, numbers, or expressions. Additionally you can use")
    time.sleep(0.3)
    print("the end function to change the end, that's because there")
    time.sleep(0.3)
    print("is a default newline character at the end of each print")
    time.sleep(0.3)
    print("it's invisible but it's there so let's get into it now.\n")
    time.sleep(0.3)

    # Examples
    print(f"\n{bold('Example 1: Using Print')}")
    time.sleep(0.3)
    print("\nINPUT:\nprint('Hello, World!')")
    time.sleep(0.3)
    print("\nOUTPUT:\nHello, World!\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)
    
    print(f"{bold('Example 2: Using End')}")
    time.sleep(0.3)
    print("\nINPUT:\nprint('Hello', end='-')")
    time.sleep(0.3)
    print("\nOUTPUT:\nHello-")
    time.sleep(0.3)
    print("\nExplanation: In this example the end would be - and not")
    print("             a new line character.\n")

# Input & Variables Lesson
def inputs():
    print(f"\n========== {bold(bright_magenta('INPUT & VARIABLES'))} ==========")
    time.sleep(0.3)
    print("The input() function allows you to take input from the user")
    time.sleep(0.3)
    print("and store it in a variable for later use. Variables are")
    time.sleep(0.3)
    print("used to store data values like text or numbers. Let's see")
    time.sleep(0.3)
    print("some examples now.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Using Input')}")
    time.sleep(0.3)
    print("INPUT:\nname = input('Enter your name: ')\nprint('Hello, ' + name)")
    time.sleep(0.3)
    print("\nOUTPUT:\nEnter your name: Alice\nHello, Alice\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Giving Value in Variable')}")
    time.sleep(0.3)
    print("INPUT:\nname = 'Ace'\nprint('Hello ' + name)")
    time.sleep(0.3)
    print("OUTPUT:\nHello Ace")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 3: Using Variables')}")
    time.sleep(0.3)
    print("INPUT:\nage = 25\nprint('You are ' + str(age) + ' years old.')")
    time.sleep(0.3)
    print("\nOUTPUT:\nYou are 25 years old.\n")
    time.sleep(0.3)
    print("Explanation: In this example we stored the number 25 in the")
    print("             variable age and then printed it out.")
    time.sleep(0.3)
    print("Note: You can also use , as alternative to + for concatenation in print.")

# Escape Sequences Lesson
def escape_sequences():
    print(f"\n========== {bold(bright_magenta('ESCAPE SEQUENCES'))} ==========")
    time.sleep(0.3)
    print("Escape sequences are special characters used in strings to")
    time.sleep(0.3)
    print("represent certain whitespace or control characters. They")
    time.sleep(0.3)
    print("begin with a backslash (\\) followed by a specific letter.")
    time.sleep(0.3)
    print("Let's look at some common escape sequences now.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Newline (\\n)')}")
    time.sleep(0.3)
    print("INPUT:\nprint('Hello\\nWorld!')")
    time.sleep(0.3)
    print("\nOUTPUT:\nHello\nWorld!\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Tab (\\t)')}")
    time.sleep(0.3)
    print("INPUT:\nprint('Hello\\tWorld!')")
    time.sleep(0.3)
    print("\nOUTPUT:\nHello\tWorld!\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 3: Backslash (\\\\)')}")
    time.sleep(0.3)
    print("INPUT:\nprint('This is a backslash: \\\\')")
    time.sleep(0.3)
    print("\nOUTPUT:\nThis is a backslash: \\\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 4: Single Quote (\\\')')}")
    time.sleep(0.3)
    print("INPUT:\nprint('It\\'s sunny today!')")
    time.sleep(0.3)
    print("\nOUTPUT:\nIt's sunny today!\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 5: Double Quote (\\\")')}")
    time.sleep(0.3)
    print('INPUT:\nprint("He said \\"Hello\\"")')
    time.sleep(0.3)
    print('\nOUTPUT:\nHe said "Hello"\n')
    time.sleep(0.3)

# Length Lesson
def length():
    print(f"\n========== {bold(bright_magenta('LENGTH'))} ==========")
    time.sleep(0.3)
    print("The len() function is used to determine the length of")
    time.sleep(0.3)
    print("a string, list, or other iterable. It returns the number")
    time.sleep(0.3)
    print("of items in the object.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Length of a String')}")
    time.sleep(0.3)
    print("INPUT:\ntext = 'Hello World'\nprint(len(text))")
    time.sleep(0.3)
    print("\nOUTPUT:\n11\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Length of a List')}")
    time.sleep(0.3)
    print("INPUT:\nnumbers = [1, 2, 3, 4, 5]\nprint(len(numbers))")
    time.sleep(0.3)
    print("\nOUTPUT:\n5\n")
    time.sleep(0.3)
    input(green('\nPress Enter to continue...'))


# Eval Lesson
def evals():
    print(f"\n========== {bold(bright_magenta('EVAL & TYPE FUNCTIONS'))} ==========")
    time.sleep(0.3)
    print("The eval() function takes a string and evaluates it as a Python expression.")
    time.sleep(0.3)
    print("It returns the result, allowing you to dynamically compute values.")
    time.sleep(0.3)
    print("Python also provides functions to convert data types or check them:")
    time.sleep(0.3)
    print("- int()   : converts a value to an integer")
    time.sleep(0.3)
    print("- float() : converts a value to a floating-point number")
    time.sleep(0.3)
    print("- str()   : converts a value to a string")
    time.sleep(0.3)
    print("- type()  : shows the data type of a value\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Evaluating a Mathematical Expression')}")
    time.sleep(0.3)
    print("INPUT:\nexpression = '2 + 3 * 4'\nresult = eval(expression)\nprint(result)")
    time.sleep(0.3)
    print("\nOUTPUT:\n14\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Using int(), float(), str(), type()')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("x = '123'")
    time.sleep(0.3)
    print("y = int(x)   # convert string to integer")
    time.sleep(0.3)
    print("z = float(x) # convert string to float")
    time.sleep(0.3)
    print("s = str(y)   # convert integer back to string")
    time.sleep(0.3)
    print("print(y, z, s)")
    time.sleep(0.3)
    print("print(type(y), type(z), type(s))")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("123 123.0 123")
    time.sleep(0.3)
    print("<class 'int'> <class 'float'> <class 'str'>\n")

# END OF BASICS LESSONS

# Operators Lessons

# Arithmetic Operators Lesson
def arithmetic():
    print(f"\n========== {bold(bright_magenta('ARITHMETIC OPERATORS'))} ==========")
    time.sleep(0.3)
    print("Arithmetic operators are used to perform mathematical")
    time.sleep(0.3)
    print("operations like addition, subtraction, multiplication,")
    time.sleep(0.3)
    print("and division. There's also floor division, modulus,")
    time.sleep(0.3)
    print("and exponentiation. Examples?\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example: Basic Arithmetic Operations')}")
    time.sleep(0.3)
    print("INPUT:\na = 10\nb = 3\n")
    time.sleep(0.3)
    print("print('Addition:', a + b)")
    time.sleep(0.3)
    print("print('Subtraction:', a - b)")
    time.sleep(0.3)
    print("print('Multiplication:', a * b)")
    time.sleep(0.3)
    print("print('Division:', a / b)")
    time.sleep(0.3)
    print("print('Floor Division:', a // b)")
    time.sleep(0.3)
    print("print('Modulus:', a % b)")
    time.sleep(0.3)
    print("print('Exponentiation:', a ** b)")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Addition: 13")
    time.sleep(0.3)
    print("Subtraction: 7")
    time.sleep(0.3)
    print("Multiplication: 30")
    time.sleep(0.3)
    print("Division: 3.3333333333333335")
    time.sleep(0.3)
    print("Floor Division: 3")
    time.sleep(0.3)
    print("Modulus: 1")
    time.sleep(0.3)
    print("Exponentiation: 1000\n")
    time.sleep(0.3)

# Assigntment Operators Lesson
def assignment():
    print(f"\n========== {bold(bright_magenta('ASSIGNMENT OPERATORS'))} ==========")
    time.sleep(0.3)
    print("Assignment operators are used to assign values to")
    time.sleep(0.3)
    print("variables. They can also perform operations and")
    time.sleep(0.3)
    print("assign the result to the variable in one step.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example: Basic Assignment Operations')}")
    time.sleep(0.3)
    print("INPUT:\nx = 5\n")
    time.sleep(0.3)
    print("x += 3  # Equivalent to x = x + 3")
    time.sleep(0.3)
    print("print('After += 3:', x)")
    time.sleep(0.3)
    print("x *= 2  # Equivalent to x = x * 2")
    time.sleep(0.3)
    print("print('After *= 2:', x)")
    time.sleep(0.3)
    print("x -= 4  # Equivalent to x = x - 4")
    time.sleep(0.3)
    print("print('After -= 4:', x)")
    time.sleep(0.3)
    print("x /= 2  # Equivalent to x = x / 2")
    time.sleep(0.3)
    print("print('After /= 2:', x)")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("After += 3: 8")
    time.sleep(0.3)
    print("After *= 2: 16")
    time.sleep(0.3)
    print("After -= 4: 12")
    time.sleep(0.3)
    print("After /= 2: 6.0\n")
    time.sleep(0.3)

# Comparison Operators Lesson
def comparison():
    print(f"\n========== {bold(bright_magenta('COMPARISON OPERATORS'))} ==========")
    time.sleep(0.3)
    print("Comparison operators are used to compare two values.")
    time.sleep(0.3)
    print("They return a boolean value (True or False) based")
    time.sleep(0.3)
    print("on the comparison result.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example: Basic Comparison Operations')}")
    time.sleep(0.3)
    print("INPUT:\na = 10\nb = 20\n")
    time.sleep(0.3)
    print("print('a == b:', a == b)") 
    time.sleep(0.3)
    print("print('a != b:', a != b)")
    time.sleep(0.3)
    print("print('a > b:', a > b)")
    time.sleep(0.3)
    print("print('a < b:', a < b)")
    time.sleep(0.3)
    print("print('a >= b:', a >= b)")
    time.sleep(0.3)
    print("print('a <= b:', a <= b)")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("a == b: False")
    time.sleep(0.3)
    print("a != b: True")
    time.sleep(0.3)
    print("a > b: False")
    time.sleep(0.3)
    print("a < b: True")
    time.sleep(0.3)
    print("a >= b: False")
    time.sleep(0.3)
    print("a <= b: True\n")
    time.sleep(0.3)

# Logical Operators Lesson
def logical():
    print(f"\n========== {bold(bright_magenta('LOGICAL OPERATORS'))} ==========")
    time.sleep(0.3)
    print("Logical operators are used to combine conditional")
    time.sleep(0.3)
    print("statements. The main logical operators are and, or,")
    time.sleep(0.3)
    print("and not.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Using \'and\' Operator')}")
    time.sleep(0.3)
    print("INPUT:\na = 10\nb = 20\n")
    time.sleep(0.3)
    print("print('a > 5 and b < 25:', a > 5 and b < 25)")
    time.sleep(0.3)
    print("\nOUTPUT:\nTrue\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Using \'or\' Operator')}")
    time.sleep(0.3)
    print("INPUT:\nprint('a < 5 or b < 25:', a < 5 or b < 25)")
    time.sleep(0.3)
    print("\nOUTPUT:\nTrue\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 3: Using \'not\' Operator')}")
    time.sleep(0.3)
    print("INPUT:\nprint('not (a > 5):', not (a > 5))")
    time.sleep(0.3)
    print("\nOUTPUT:\nFalse\n")
    time.sleep(0.3)

# End of Operators Lessons

# Conditional Statements Lessons

# If Elif Else Lesson
def if_elif_else():
    print(f"\n========== {bold(bright_magenta('IF ELIF ELSE'))} ==========")
    time.sleep(0.3)
    print("Conditional statements allow you to execute certain")
    time.sleep(0.3)
    print("blocks of code based on specific conditions using if,")
    time.sleep(0.3)
    print("elif, and else.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Using if Statement')}")
    time.sleep(0.3)
    print("INPUT:\nnum = 10\n")
    time.sleep(0.3)
    print("if num > 5:")
    time.sleep(0.3)
    print("    print('Number is greater than 5')")
    time.sleep(0.3)
    print("\nOUTPUT:\nNumber is greater than 5\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Using if-else Statement')}")
    time.sleep(0.3)
    print("INPUT:\nnum = 3\n")
    time.sleep(0.3)
    print("if num > 5:")
    time.sleep(0.3)
    print("    print('Number is greater than 5')")
    time.sleep(0.3)
    print("else:")
    time.sleep(0.3)
    print("    print('Number is 5 or less')")
    time.sleep(0.3)
    print("\nOUTPUT:\nNumber is 5 or less\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 3: Using if-elif-else Statement')}")
    time.sleep(0.3)
    print("INPUT:\nnum = 5\n")
    time.sleep(0.3)
    print("if num > 5:")
    time.sleep(0.3)
    print("    print('Number is greater than 5')")
    time.sleep(0.3)
    print("elif num == 5:")
    time.sleep(0.3)
    print("    print('Number is equal to 5')")
    time.sleep(0.3)
    print("else:")
    time.sleep(0.3)
    print("    print('Number is less than 5')")
    time.sleep(0.3)
    print("\nOUTPUT:\nNumber is equal to 5\n")
    time.sleep(0.3)

    print(f"{bold('Note:')} Common mistake is using = instead of == for some comparison.")
    time.sleep(0.3)

# Nested Conditions Lesson
def nested():
    print(f"\n========== {bold(bright_magenta('NESTED CONDITIONS'))} ==========")
    time.sleep(0.3)
    print("Nested conditions are conditional statements placed")
    time.sleep(0.3)
    print("inside other conditional statements. This allows for")
    time.sleep(0.3)
    print("more complex decision-making in your code.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Basic Nested if Statements')}")
    time.sleep(0.3)
    print("INPUT:\nnum = 15\n")
    time.sleep(0.3)
    print("if num > 10:")
    time.sleep(0.3)
    print("    if num < 20:")
    time.sleep(0.3)
    print("        print('Number is between 10 and 20')")
    time.sleep(0.3)
    print("\nOUTPUT:\nNumber is between 10 and 20\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Nested if-else Statements')}")
    time.sleep(0.3)
    print("INPUT:\nnum = 25\n")
    time.sleep(0.3)
    print("if num > 10:")
    time.sleep(0.3)
    print("    if num < 20:")
    time.sleep(0.3)
    print("        print('Number is between 10 and 20')")
    time.sleep(0.3)
    print("    else:")
    time.sleep(0.3)
    print("        print('Number is greater than or equal to 20')")
    time.sleep(0.3)
    print("\nOUTPUT:\nNumber is greater than or equal to 20\n")
    time.sleep(0.3)

    print("Explanation: In this example, the outer if checks if num is")
    time.sleep(0.3)
    print("greater than 10. If true, the inner if-else checks if num")
    time.sleep(0.3)
    print("is less than 20 or not, and prints the appropriate message.")
    time.sleep(0.3)

# Combining Conditions Lesson
def combining():
    print(f"\n========== {bold(bright_magenta('COMBINING CONDITIONS'))} ==========")
    time.sleep(0.3)
    print("Combining conditions using logical operators (and, or, not)")
    time.sleep(0.3)
    print("allows you to create more complex conditional statements.")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Using \'and\' to Combine Conditions')}")
    time.sleep(0.3)
    print("INPUT:\nnum = 15\n")
    time.sleep(0.3)
    print("if num > 10 and num < 20:")
    time.sleep(0.3)
    print("    print('Number is between 10 and 20')")
    time.sleep(0.3)
    print("\nOUTPUT:\nNumber is between 10 and 20\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Using \'or\' to Combine Conditions')}")
    time.sleep(0.3)
    print("INPUT:\nnum = 5\n")
    time.sleep(0.3)
    print("if num < 10 or num > 20:")
    time.sleep(0.3)
    print("    print('Number is either less than 10 or greater than 20')")
    time.sleep(0.3)
    print("\nOUTPUT:\nNumber is either less than 10 or greater than 20\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 3: Using \'not\' to Negate a Condition')}")
    time.sleep(0.3)
    print("INPUT:\nnum = 15\n")
    time.sleep(0.3)
    print("if not (num < 10):")
    time.sleep(0.3)
    print("    print('Number is 10 or greater')")
    time.sleep(0.3)
    print("\nOUTPUT:\nNumber is 10 or greater\n")
    time.sleep(0.3)

# End of Conditional Statements Lessons

# Loops Lessons

# For Loops Lesson
def for_loops():
    print(f"\n========== {bold(bright_magenta('FOR LOOPS'))} ==========")
    time.sleep(0.3)
    print("For loops are used to iterate over a sequence (like")
    time.sleep(0.3)
    print("a list, tuple, or string) or other iterable objects.")
    time.sleep(0.3)
    print("They allow you to execute a block of code multiple times.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Basic For Loop')}")
    time.sleep(0.3)
    print("INPUT:\nfor i in range(5):")
    time.sleep(0.3)
    print("    print('Iteration', i)")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Iteration 0")
    time.sleep(0.3)
    print("Iteration 1")
    time.sleep(0.3)
    print("Iteration 2")
    time.sleep(0.3)
    print("Iteration 3")
    time.sleep(0.3)
    print("Iteration 4\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Iterating Over a List')}")
    time.sleep(0.3)
    print("INPUT:\nnumbers = [10, 20, 30, 40, 50]\n")
    time.sleep(0.3)
    print("for num in numbers:")
    time.sleep(0.3)
    print("    print('Number:', num)")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Number: 10")
    time.sleep(0.3)
    print("Number: 20")
    time.sleep(0.3)
    print("Number: 30")
    time.sleep(0.3)
    print("Number: 40")
    time.sleep(0.3)
    print("Number: 50\n")
    time.sleep(0.3)

    print("Explanation: In the first example, the for loop iterates")
    time.sleep(0.3)
    print("over a range of numbers from 0 to 4, printing each iteration.")
    time.sleep(0.3)
    print("In the second example, it iterates over a list of numbers,")
    time.sleep(0.3)
    print("printing each number in the list.")
    time.sleep(0.3)

# While Loops Lesson
def while_loops():
    print(f"\n========== {bold(bright_magenta('WHILE LOOPS'))} ==========")
    time.sleep(0.3)
    print("While loops repeatedly execute a block of code as long")
    time.sleep(0.3)
    print("as a specified condition is true.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Basic While Loop')}")
    time.sleep(0.3)
    print("INPUT:\ncount = 0\n")
    time.sleep(0.3)
    print("while count < 5:")
    time.sleep(0.3)
    print("    print('Count is', count)")
    time.sleep(0.3)
    print("    count += 1")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Count is 0")
    time.sleep(0.3)
    print("Count is 1")
    time.sleep(0.3)
    print("Count is 2")
    time.sleep(0.3)
    print("Count is 3")
    time.sleep(0.3)
    print("Count is 4\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: While True Loop with Break')}")
    time.sleep(0.3)
    print("INPUT:\ncount = 0\n")
    time.sleep(0.3)
    print("while True:")
    time.sleep(0.3)
    print("    print('Count is', count)")
    time.sleep(0.3)
    print("    count += 1")
    time.sleep(0.3)
    print("    if count >= 5:")
    time.sleep(0.3)
    print("        break")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Count is 0")
    time.sleep(0.3)
    print("Count is 1")
    time.sleep(0.3)
    print("Count is 2")
    time.sleep(0.3)
    print("Count is 3")
    time.sleep(0.3)
    print("Count is 4\n")
    time.sleep(0.3)
    print("Explanation: In this example, the while True loop runs indefinitely")
    time.sleep(0.3)
    print("until the break statement is encountered when count reaches 5.")
    time.sleep(0.3)

# Nested Loops Lesson
def nested_loops():
    print(f"\n========== {bold(bright_magenta('NESTED LOOPS'))} ==========")
    time.sleep(0.3)
    print("Nested loops are loops placed inside other loops.")
    time.sleep(0.3)
    print("They allow you to iterate over multi-dimensional")
    time.sleep(0.3)
    print("data structures like lists of lists.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example: Basic Nested For Loops')}")
    time.sleep(0.3)
    print("INPUT:\nmatrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\n")
    time.sleep(0.3)
    print("for row in matrix:")
    time.sleep(0.3)
    print("    for item in row:")
    time.sleep(0.3)
    print("        print(item, end=' ')")
    time.sleep(0.3)
    print("    print()  # New line after each row")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("1 2 3 ")
    time.sleep(0.3)
    print("4 5 6 ")
    time.sleep(0.3)
    print("7 8 9 \n")
    time.sleep(0.3)

    print("Explanation: In this example, the outer loop iterates over")
    time.sleep(0.3)
    print("each row of the matrix, while the inner loop iterates over")
    time.sleep(0.3)
    print("each item in the current row, printing them in a formatted way.")
    time.sleep(0.3)

# Loop Control Statements Lesson
def loop_control():
    print(f"\n========== {bold(bright_magenta('LOOP CONTROL STATEMENTS'))} ==========")
    time.sleep(0.3)
    print("Loop control statements like break and continue allow")
    time.sleep(0.3)
    print("you to modify the behavior of loops. 'break' exits")
    time.sleep(0.3)
    print("the loop, while 'continue' skips to the next iteration.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Using break Statement')}")
    time.sleep(0.3)
    print("INPUT:\nfor i in range(10):")
    time.sleep(0.3)
    print("    if i == 5:")
    time.sleep(0.3)
    print("        break")
    time.sleep(0.3)
    print("    print('Iteration', i)")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Iteration 0")
    time.sleep(0.3)
    print("Iteration 1")
    time.sleep(0.3)
    print("Iteration 2")
    time.sleep(0.3)
    print("Iteration 3")
    time.sleep(0.3)
    print("Iteration 4\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Using continue Statement')}")
    time.sleep(0.3)
    print("INPUT:\nfor i in range(10):")
    time.sleep(0.3)
    print("    if i % 2 == 0:")
    time.sleep(0.3)
    print("        continue")
    time.sleep(0.3)
    print("    print('Odd Number:', i)")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Odd Number: 1")
    time.sleep(0.3)
    print("Odd Number: 3")
    time.sleep(0.3)
    print("Odd Number: 5")
    time.sleep(0.3)
    print("Odd Number: 7")
    time.sleep(0.3)
    print("Odd Number: 9\n")
    time.sleep(0.3)

    print("Explanation: In the first example, the loop exits when i equals 5.")
    time.sleep(0.3)
    print("In the second example, even numbers are skipped, and only odd")
    time.sleep(0.3)
    print("numbers are printed.")
    time.sleep(0.3)

# End of Loops Lessons

# List & Functions Lessons

# Lists Lesson
def lists():
    print(f"\n========== {bold(bright_yellow('LISTS'))} ==========")
    time.sleep(0.3)
    print("Lists are used to store multiple items in a single variable.")
    time.sleep(0.3)
    print("They are ordered, changeable, and allow duplicate values.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Creating and Accessing a List')}")
    time.sleep(0.3)
    print("INPUT:\nmy_list = [10, 20, 30, 40]")
    time.sleep(0.3)
    print("print(my_list[0])  # Access first item")
    time.sleep(0.3)
    print("\nOUTPUT:\n10\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Adding and Removing Items')}")
    time.sleep(0.3)
    print("INPUT:\nmy_list = [1, 2, 3]")
    time.sleep(0.3)
    print("my_list.append(4)")
    time.sleep(0.3)
    print("my_list.remove(2)")
    time.sleep(0.3)
    print("print(my_list)")
    time.sleep(0.3)
    print("\nOUTPUT:\n[1, 3, 4]\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 3: Indexing in Lists')}")
    time.sleep(0.3)
    print("INPUT:\nmy_list = ['a', 'b', 'c', 'd']")
    time.sleep(0.3)
    print("print(my_list[1])  # Access second item")
    time.sleep(0.3)
    print("print(my_list[-1]) # Access last item")
    time.sleep(0.3)
    print("\nOUTPUT:\nb\nd\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 4: Looping through a List')}")
    time.sleep(0.3)
    print("INPUT:\nmy_list = ['apple', 'banana', 'cherry']")
    time.sleep(0.3)
    print("for fruit in my_list:")
    time.sleep(0.3)
    print("    print(fruit)")
    time.sleep(0.3)
    print("\nOUTPUT:\napple\nbanana\ncherry\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 5: Using insert()')}")
    time.sleep(0.3)
    print("INPUT:\nmy_list = [1, 2, 4, 5]")
    time.sleep(0.3)
    print("my_list.insert(2, 3)  # Insert 3 at index 2")
    time.sleep(0.3)
    print("print(my_list)")
    time.sleep(0.3)
    print("\nOUTPUT:\n[1, 2, 3, 4, 5]\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 6: Using pop()')}")
    time.sleep(0.3)
    print("INPUT:\nmy_list = [10, 20, 30, 40]")
    time.sleep(0.3)
    print("my_list.pop(2)  # Remove item at index 2 (30)")
    time.sleep(0.3)
    print("print(my_list)")
    time.sleep(0.3)
    print("\nOUTPUT:\n[10, 20, 40]\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 7: Using sort()')}")
    time.sleep(0.3)
    print("INPUT:\nmy_list = [4, 2, 5, 1, 3]")
    time.sleep(0.3)
    print("my_list.sort()")
    time.sleep(0.3)
    print("print(my_list)")
    time.sleep(0.3)
    print("\nOUTPUT:\n[1, 2, 3, 4, 5]\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

# FUNCTIONS LESSON
def functions():
    print(f"\n========== {bold(bright_cyan('FUNCTIONS'))} ==========")
    time.sleep(0.3)
    print("Functions are reusable blocks of code that perform a specific task.")
    time.sleep(0.3)
    print("They help make programs organized, modular, and easier to read.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Defining and Calling a Function')}")
    time.sleep(0.3)
    print("INPUT:\ndef greet():")
    time.sleep(0.3)
    print("    print('Hello!')")
    time.sleep(0.3)
    print("greet()")
    time.sleep(0.3)
    print("\nOUTPUT:\nHello!\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Function with Parameters')}")
    time.sleep(0.3)
    print("INPUT:\ndef greet(name):")
    time.sleep(0.3)
    print("    print('Hello,', name)")
    time.sleep(0.3)
    print("greet('Alice')")
    time.sleep(0.3)
    print("\nOUTPUT:\nHello, Alice\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 3: Function with Return Value')}")
    time.sleep(0.3)
    print("INPUT:\ndef add(a, b):")
    time.sleep(0.3)
    print("    return a + b")
    time.sleep(0.3)
    print("result = add(5, 3)")
    time.sleep(0.3)
    print("print(result)")
    time.sleep(0.3)
    print("\nOUTPUT:\n8\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 4: Function with Default Parameters')}")
    time.sleep(0.3)
    print("INPUT:\ndef greet(name='User'):")
    time.sleep(0.3)
    print("    print('Hello,', name)")
    time.sleep(0.3)
    print("greet()")
    time.sleep(0.3)
    print("greet('Bob')")
    time.sleep(0.3)
    print("\nOUTPUT:\nHello, User\nHello, Bob\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 5: Function with Multiple Return Values')}")
    time.sleep(0.3)
    print("INPUT:\ndef operations(x, y):")
    time.sleep(0.3)
    print("    return x+y, x*y")
    time.sleep(0.3)
    print("sum_result, product = operations(4, 5)")
    time.sleep(0.3)
    print("print('Sum:', sum_result)")
    time.sleep(0.3)
    print("print('Product:', product)")
    time.sleep(0.3)
    print("\nOUTPUT:\nSum: 9\nProduct: 20\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

# DEF VARIABLES LESSON
def defs():
    print(f"\n========== {bold(bright_magenta('DEF VARIABLES'))} ==========")
    time.sleep(0.3)
    print("DEF variables allow you to store values or logic inside functions.")
    time.sleep(0.3)
    print("You can call these variables/functions whenever needed.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Simple DEF Variable')}")
    time.sleep(0.3)
    print("INPUT:\ndef greet():")
    time.sleep(0.3)
    print("    message = 'Hello World!'")
    time.sleep(0.3)
    print("    return message\n")
    time.sleep(0.3)
    print("OUTPUT when calling greet():")
    time.sleep(0.3)
    print("Hello World!\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: DEF Variable with Parameters')}")
    time.sleep(0.3)
    print("INPUT:\ndef greet_name(name):")
    time.sleep(0.3)
    print("    message = f'Hello {name}!'")
    time.sleep(0.3)
    print("    return message\n")
    time.sleep(0.3)
    print("OUTPUT when calling greet_name('Alice'):")
    time.sleep(0.3)
    print("Hello Alice!\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 3: DEF Variable with Multiple Parameters')}")
    time.sleep(0.3)
    print("INPUT:\ndef add_numbers(a, b):")
    time.sleep(0.3)
    print("    result = a + b")
    time.sleep(0.3)
    print("    return result\n")
    time.sleep(0.3)
    print("OUTPUT when calling add_numbers(5, 7):")
    time.sleep(0.3)
    print("12\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 4: DEF Variable without Return (Direct Print)')}")
    time.sleep(0.3)
    print("INPUT:\ndef say_hello():")
    time.sleep(0.3)
    print("    print('Hello directly from the function!')\n")
    time.sleep(0.3)
    print("OUTPUT when calling say_hello():")
    time.sleep(0.3)
    print("Hello directly from the function!\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 5: Importing DEF Variables from Another File')}")
    time.sleep(0.3)
    print("INPUT (in file 'my_module.py'):\ndef greet():")
    time.sleep(0.3)
    print("    message = 'Hello from another file!'")
    time.sleep(0.3)
    print("    return message\n")
    time.sleep(0.3)
    print("INPUT (in main program file):\nfrom my_module import greet")
    time.sleep(0.3)
    print("print(greet())\n")
    time.sleep(0.3)
    print("OUTPUT:\nHello from another file!\n")
    time.sleep(0.3)
    print("Explanation: By using 'from filename import function', you can access DEF variables and functions defined in another file.")
    time.sleep(0.3)
    print("This is useful for organizing code into modules.\n")
    time.sleep(0.3)

# IMPORTING RANDOM LESSON
def importing_random():
    print(f"\n========== {bold(bright_green('IMPORTING RANDOM'))} ==========")
    time.sleep(0.3)
    print("The 'random' module allows you to generate random numbers and make random selections.")
    time.sleep(0.3)
    print("First, you need to import it using: import random\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Generating a Random Integer')}")
    time.sleep(0.3)
    print("INPUT:\nimport random")
    time.sleep(0.3)
    print("num = random.randint(1, 10)")
    time.sleep(0.3)
    print("print(num)\n")
    time.sleep(0.3)
    print("OUTPUT: (random number between 1 and 10)\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Random Choice from a List')}")
    time.sleep(0.3)
    print("INPUT:\nimport random")
    time.sleep(0.3)
    print("fruits = ['apple', 'banana', 'cherry']")
    time.sleep(0.3)
    print("choice = random.choice(fruits)")
    time.sleep(0.3)
    print("print(choice)\n")
    time.sleep(0.3)
    print("OUTPUT: (randomly selected fruit from the list)\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 3: Shuffling a List')}")
    time.sleep(0.3)
    print("INPUT:\nimport random")
    time.sleep(0.3)
    print("numbers = [1, 2, 3, 4, 5]")
    time.sleep(0.3)
    print("random.shuffle(numbers)")
    time.sleep(0.3)
    print("print(numbers)\n")
    time.sleep(0.3)
    print("OUTPUT: (list randomly shuffled)\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 4: Generating a Random Float')}")
    time.sleep(0.3)
    print("INPUT:\nimport random")
    time.sleep(0.3)
    print("num = random.random()")
    time.sleep(0.3)
    print("print(num)\n")
    time.sleep(0.3)
    print("OUTPUT: (random float between 0.0 and 1.0)\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

# DICTIONARIES LESSON
def dictionaries():
    print(f"\n========== {bold(bright_red('DICTIONARIES'))} ==========")
    time.sleep(0.3)
    print("A dictionary is a collection of key-value pairs in Python.")
    time.sleep(0.3)
    print("Each key maps to a value. Keys are unique.\n")
    time.sleep(0.3)

    # Examples
    print(f"{bold('Example 1: Creating a Dictionary')}")
    time.sleep(0.3)
    print("INPUT:\nstudent = {'name': 'Alice', 'age': 20, 'course': 'ITCS'}")
    time.sleep(0.3)
    print("print(student)\n")
    time.sleep(0.3)
    print("OUTPUT:\n{'name': 'Alice', 'age': 20, 'course': 'ITCS'}\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 2: Accessing Values')}")
    time.sleep(0.3)
    print("INPUT:\nprint(student['name'])")
    time.sleep(0.3)
    print("print(student['age'])\n")
    time.sleep(0.3)
    print("OUTPUT:\nAlice\n20\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 3: Modifying Values')}")
    time.sleep(0.3)
    print("INPUT:\nstudent['age'] = 21")
    time.sleep(0.3)
    print("print(student['age'])\n")
    time.sleep(0.3)
    print("OUTPUT:\n21\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 4: Adding and Removing Key-Value Pairs')}")
    time.sleep(0.3)
    print("INPUT:\nstudent['grade'] = 'A'")
    time.sleep(0.3)
    print("del student['course']")
    time.sleep(0.3)
    print("print(student)\n")
    time.sleep(0.3)
    print("OUTPUT:\n{'name': 'Alice', 'age': 21, 'grade': 'A'}\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

    print(f"{bold('Example 5: Looping Through a Dictionary')}")
    time.sleep(0.3)
    print("INPUT:\nfor key, value in student.items():")
    time.sleep(0.3)
    print("    print(key, value)\n")
    time.sleep(0.3)
    print("OUTPUT:")
    time.sleep(0.3)
    print("name Alice")
    time.sleep(0.3)
    print("age 21")
    time.sleep(0.3)
    print("grade A\n")
    time.sleep(0.3)
    input(green('\nPress Enter to see next example: '))
    time.sleep(0.3)

# End of List & Functions

# Challenges

# Challenge 1: Diamond with Name
def challenge_1():
    print(f"\n========== {bold(bright_magenta('CHALLENGE 1'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Ask the user to enter their full name.")
    time.sleep(0.3)
    print("- Create a diamond shape using '*' characters.")
    time.sleep(0.3)
    print("- Place the user's name in the middle of the diamond.\n")
    time.sleep(0.3)

    input(green('Press Enter to see the Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example (if user enters 'ADRIAN'):")
    time.sleep(0.3)
    print("\t\t\t\t\t*")
    time.sleep(0.3)
    print("\t\t\t\t*\t\t*")
    time.sleep(0.3)
    print("\t\t\t*\t\t\t\t*")
    time.sleep(0.3)
    print("\t\t*\t\t      Hello,\t\t\t*")
    time.sleep(0.3)
    print("\t*\t\t\t\tADRIAN\t\t\t\t*")
    time.sleep(0.3)
    print("\t\t*\t\t\t\t\t\t*")
    time.sleep(0.3)
    print("\t\t\t*\t\t\t\t*")
    time.sleep(0.3)
    print("\t\t\t\t*\t\t*")
    time.sleep(0.3)
    print("\t\t\t\t\t*")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use print() with tabs '\\t' or spaces to create the shape.")
    time.sleep(0.3)
    print("- The user's name should be printed in the middle row.")
    time.sleep(0.3)
    print("- Think of the diamond as layers: top, middle, bottom.")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 2: ATM Denominator Breakdown
def challenge_2():
    print(f"\n========== {bold(bright_yellow('CHALLENGE 2'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Ask the user to input an amount to deposit.")
    time.sleep(0.3)
    print("- Break down the amount into bills: 1000, 500, 200, 100, 50, 20, 10, 5, 1.")
    time.sleep(0.3)
    print("- Display how many of each bill is needed.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example (Amount = 2876):")
    time.sleep(0.3)
    print("2 - 1000")
    time.sleep(0.3)
    print("1 - 500")
    time.sleep(0.3)
    print("1 - 200")
    time.sleep(0.3)
    print("1 - 100")
    time.sleep(0.3)
    print("1 - 50")
    time.sleep(0.3)
    print("1 - 20")
    time.sleep(0.3)
    print("0 - 10")
    time.sleep(0.3)
    print("1 - 5")
    time.sleep(0.3)
    print("1 - 1\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use floor division '//' to calculate number of bills.")
    time.sleep(0.3)
    print("- Use modulo '%' to get remaining amount for next denomination.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 3: Student Discount Checker
def challenge_3():
    print(f"\n========== {bold(bright_cyan('CHALLENGE 3'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Ask the user's name and fare amount.")
    time.sleep(0.3)
    print("- Ask if the user is a student (yes/no).")
    time.sleep(0.3)
    print("- Apply 20% discount if student and show total fee.")
    time.sleep(0.3)
    print("- Show a message if not eligible.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example (Fare = 500, Student = yes):")
    time.sleep(0.3)
    print("You're discounted!")
    time.sleep(0.3)
    print("Your total fee after discount is: 400.0\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use if-else statements to check student status.")
    time.sleep(0.3)
    print("- Calculate discount using multiplication and subtraction.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 4: Manga & Manhwa Recommender
def challenge_4():
    print(f"\n========== {bold(bright_green('CHALLENGE 4'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Ask the user if they prefer manga or manhwa.")
    time.sleep(0.3)
    print("- Ask for their preferred genre (action, romance, comedy, sports, horror).")
    time.sleep(0.3)
    print("- Ask for their preferred era (2000s or 2010s).")
    time.sleep(0.3)
    print("- Ask for duration preference (short, medium, long).")
    time.sleep(0.3)
    print("- Suggest a title based on their choices.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example:")
    time.sleep(0.3)
    print("Inputs: manga, action, 2010s, short")
    time.sleep(0.3)
    print("Suggested Title: Attack on Titan (139 chapters)")
    time.sleep(0.3)
    print("\nInputs: manhwa, romance, 2010s, long")
    time.sleep(0.3)
    print("Suggested Title: Love Revolution (500+ chapters)\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use input() to gather user preferences and store in variables.")
    time.sleep(0.3)
    print("- Use nested if/elif statements to determine the recommended title.")
    time.sleep(0.3)
    print("- Consider .lower().strip() on user input to handle variations.")
    time.sleep(0.3)
    print("- Use print() to show the suggestion based on the selected options.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 5: Factorial Calculator
def challenge_5():
    print(f"\n========== {bold(bright_red('CHALLENGE 5'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Ask the user to input a number.")
    time.sleep(0.3)
    print("- Compute the factorial of the number (n! = 1 * 2 * ... * n).")
    time.sleep(0.3)
    print("- Display the result.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example:")
    time.sleep(0.3)
    print("Input: 5")
    time.sleep(0.3)
    print("The factorial of 5 is 120")
    time.sleep(0.3)
    print("\nInput: 7")
    time.sleep(0.3)
    print("The factorial of 7 is 5040\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a for loop ranging from 1 to the number (inclusive).")
    time.sleep(0.3)
    print("- Initialize a result variable to 1, then multiply it by each number in the loop.")
    time.sleep(0.3)
    print("- Use print() to display the factorial at the end.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 6: Odd Number Summation
def challenge_6():
    print(f"\n========== {bold(bright_magenta('CHALLENGE 6'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Ask the user to input 7 numbers.")
    time.sleep(0.3)
    print("- Only sum the numbers that are odd.")
    time.sleep(0.3)
    print("- Display the total sum of odd numbers.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example:")
    time.sleep(0.3)
    print("Inputs: 1, 2, 3, 4, 5, 6, 7")
    time.sleep(0.3)
    print("The sum of all odd numbers you input is: 16  (1 + 3 + 5 + 7)\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a for loop that runs 7 times to take user input each iteration.")
    time.sleep(0.3)
    print("- Use modulo '%' to check if a number is odd (num % 2 != 0).")
    time.sleep(0.3)
    print("- Add the odd numbers to a running total variable.")
    time.sleep(0.3)
    print("- Print the total sum after the loop ends.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 7: Countdown Simulator (Liftoff)
def challenge_7():
    print(f"\n========== {bold(bright_yellow('CHALLENGE 7'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Ask the user for a starting number for the countdown.")
    time.sleep(0.3)
    print("- Count down from that number to 1.")
    time.sleep(0.3)
    print("- After reaching 1, print 'Liftoff!'\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example:")
    time.sleep(0.3)
    print("Input: 5")
    time.sleep(0.3)
    print("Output:")
    time.sleep(0.3)
    for i in range(5, 0, -1):
        print(i)
        time.sleep(0.1)
    print("Liftoff!\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a for loop with range(start, 0, -1) to count down.")
    time.sleep(0.3)
    print("- Print each number inside the loop.")
    time.sleep(0.3)
    print("- After the loop ends, print 'Liftoff!'.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 8: Multiplication Table
def challenge_8():
    print(f"\n========== {bold(bright_cyan('CHALLENGE 8'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Ask the user for a number.")
    time.sleep(0.3)
    print("- Print the multiplication table of that number from 1 to 10.")
    time.sleep(0.3)
    print("- Each line should show 'number x multiplier = result'.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example:")
    time.sleep(0.3)
    num = 3
    for i in range(1, 11):
        print(f"{num} x {i} = {num * i}")
        time.sleep(0.1)
    print()
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a for loop with range(1, 11) to go from 1 to 10.")
    time.sleep(0.3)
    print("- Multiply the input number by the loop variable inside the loop.")
    time.sleep(0.3)
    print("- Print each result in the format 'number x multiplier = result'.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 9: Parrot Simulator
def challenge_9():
    print(f"\n========== {bold(bright_green('CHALLENGE 9'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Ask the user for a phrase the parrot should repeat.")
    time.sleep(0.3)
    print("- Ask the user how many times the parrot should repeat the phrase.")
    time.sleep(0.3)
    print("- Print the phrase the specified number of times, prefixed with '🦜: Squawk! Squawk!'\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example:")
    time.sleep(0.3)
    phrase = "Hello!"
    for _ in range(3):
        print(f"🦜: Squawk! Squawk! {phrase}")
        time.sleep(0.1)
    print()
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a for loop that runs from 1 to the number of repeats (inclusive).")
    time.sleep(0.3)
    print("- Use the print function inside the loop to display the parrot's phrase each iteration.")
    time.sleep(0.3)
    print("- Concatenate the squawk prefix with the user's input phrase.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 10: Reversed Staircase For Loop
def challenge_10():
    print(f"\n========== {bold(bright_red('CHALLENGE 10'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Print a reversed staircase using nested loops.")
    time.sleep(0.3)
    print("- Each row contains a decreasing number of '💚' from top to bottom.")
    time.sleep(0.3)
    print("- The first row should have the most hearts, the last row only one heart.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example:")
    time.sleep(0.3)
    for row in range(10, 0, -1):
        print("💚 " * row)
        time.sleep(0.1)
    print()
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a for loop for rows, counting down from the total number of hearts.")
    time.sleep(0.3)
    print("- Use a nested for loop to print hearts in each row.")
    time.sleep(0.3)
    print("- Use the 'end' parameter in print() to avoid line breaks for each heart.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 11: Triangle Pattern
def challenge_11():
    print(f"\n========== {bold(bright_magenta('CHALLENGE 11'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Print a triangle using 'x' characters.")
    time.sleep(0.3)
    print("- The triangle should have 10 rows.")
    time.sleep(0.3)
    print("- Each row increases the number of 'x' characters symmetrically, forming a triangle shape.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example:")
    time.sleep(0.3)
    for i in range(1, 11):
        print(" "*(10-i) + "x"*(2*i-1))
        time.sleep(0.1)
    print()
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a for loop to iterate over the rows (1 to 10).")
    time.sleep(0.3)
    print("- For each row, print spaces first to align the 'x's in the center.")
    time.sleep(0.3)
    print("- Then print 'x' characters twice minus one to maintain symmetry.")
    time.sleep(0.3)
    print("- Use the 'end' parameter in print() to keep characters on the same line before printing a new row.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 12: Pyramid Number Pattern
def challenge_12():
    print(f"\n========== {bold(bright_yellow('CHALLENGE 12'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Print a pyramid of numbers.")
    time.sleep(0.3)
    print("- Each row starts with 1, ascends to the row number, then descends back to 1.")
    time.sleep(0.3)
    print("- The pyramid should have 5 rows (or more if desired).\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example (5 rows):")
    time.sleep(0.3)
    for i in range(1, 6):
        print(" "*(5-i), end="")
        for j in range(1, i+1):
            print(j, end="")
        for j in range(i-1, 0, -1):
            print(j, end="")
        print()
        time.sleep(0.1)
    print()
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a for loop for rows from 1 to the desired number of rows.")
    time.sleep(0.3)
    print("- Print spaces first to align numbers in the center.")
    time.sleep(0.3)
    print("- Use a nested loop to print ascending numbers from 1 to the current row number.")
    time.sleep(0.3)
    print("- Use another nested loop to print descending numbers from the current row number - 1 back to 1.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 13: Odd/Even Summation
def challenge_13():
    print(f"\n========== {bold(bright_cyan('CHALLENGE 13'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Keep asking the user for numbers.")
    time.sleep(0.3)
    print("- Keep separate sums for odd and even numbers.")
    time.sleep(0.3)
    print("- Stop asking when the user inputs 0 and display the totals.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example (Inputs: 1, 2, 3, 4, 0):")
    time.sleep(0.3)
    print("Total ODD = 4 (1 + 3)")
    time.sleep(0.3)
    print("Total EVEN = 6 (2 + 4)\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a while True loop to repeatedly ask for input.")
    time.sleep(0.3)
    print("- Use modulo '%' to separate odd and even numbers.")
    time.sleep(0.3)
    print("- Break the loop if input is 0.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 14: Anime List Maker
def challenge_14():
    print(f"\n========== {bold(bright_green('CHALLENGE 14'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Ask the user to enter anime titles one by one.")
    time.sleep(0.3)
    print("- Stop asking when the user types 'exit'.")
    time.sleep(0.3)
    print("- Store all titles in a list and display them at the end.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example:")
    time.sleep(0.3)
    print("Enter Anime Title (Type 'exit' to stop): Naruto")
    time.sleep(0.3)
    print("Enter Anime Title (Type 'exit' to stop): One Piece")
    time.sleep(0.3)
    print("Enter Anime Title (Type 'exit' to stop): exit")
    time.sleep(0.3)
    print("\nYour Anime List Contains:")
    time.sleep(0.3)
    print("- Naruto")
    time.sleep(0.3)
    print("- One Piece\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a while loop to repeatedly ask for input.")
    time.sleep(0.3)
    print("- Use a list to store the entered anime titles.")
    time.sleep(0.3)
    print("- Break the loop if the user types 'exit'.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Challenge 15: Student Information System
def challenge_15():
    print(f"\n========== {bold(bright_red('CHALLENGE 15'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Create a system to manage student records.")
    time.sleep(0.3)
    print("- Include the following options:")
    time.sleep(0.3)
    print("  * Add student record")
    time.sleep(0.3)
    print("  * Print all student records")
    time.sleep(0.3)
    print("  * Search for a student record")
    time.sleep(0.3)
    print("  * Edit a student record")
    time.sleep(0.3)
    print("  * Delete a student record")
    time.sleep(0.3)
    print("  * Export records to a JSON file\n")
    time.sleep(0.3)

    input(green('Press Enter to see Desired Output Example...'))
    time.sleep(0.3)
    print("\nDesired Output Example:")
    time.sleep(0.3)
    print("===== OPTIONS =====")
    time.sleep(0.3)
    print("A = Add student record.")
    time.sleep(0.3)
    print("B = Print all student record.")
    time.sleep(0.3)
    print("C = Search student record.")
    time.sleep(0.3)
    print("D = Delete student record.")
    time.sleep(0.3)
    print("E = Edit student record.")
    time.sleep(0.3)
    print("F = Export student record.")
    time.sleep(0.3)
    print("G = Exit.\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use a dictionary to store student records with Student ID as key.")
    time.sleep(0.3)
    print("- Each record can be a list containing First Name, Last Name, Age, Section, and Course.")
    time.sleep(0.3)
    print("- Use loops to show menu repeatedly until the user exits.")
    time.sleep(0.3)
    print("- Use functions or separate code blocks to handle Add, Print, Search, Edit, Delete, and Export operations.")
    time.sleep(0.3)
    print("- For export, you can use the json module to save the dictionary to a JSON file.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Color Lesson
def colors():
    print(f"\n========== {bold(bright_magenta('COLOR ANSI CODES'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Learn how to use ANSI escape codes to add color and styles to your console output.")
    time.sleep(0.3)
    print("- Students can format text themselves using these codes.\n")
    time.sleep(0.3)

    print(f"{bold('Basic Syntax')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("print('\\033[31mHello\\033[0m')  # Red text")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Hello (in red)\n")
    time.sleep(0.3)

    print(f"{bold('Foreground Colors')}")
    time.sleep(0.3)
    print("- 30: Black")
    time.sleep(0.3)
    print("- 31: Red")
    time.sleep(0.3)
    print("- 32: Green")
    time.sleep(0.3)
    print("- 33: Yellow")
    time.sleep(0.3)
    print("- 34: Blue")
    time.sleep(0.3)
    print("- 35: Magenta")
    time.sleep(0.3)
    print("- 36: Cyan")
    time.sleep(0.3)
    print("- 37: White\n")
    time.sleep(0.3)

    print(f"{bold('Background Colors')}")
    time.sleep(0.3)
    print("- 40: Black")
    time.sleep(0.3)
    print("- 41: Red")
    time.sleep(0.3)
    print("- 42: Green")
    time.sleep(0.3)
    print("- 43: Yellow")
    time.sleep(0.3)
    print("- 44: Blue")
    time.sleep(0.3)
    print("- 45: Magenta")
    time.sleep(0.3)
    print("- 46: Cyan")
    time.sleep(0.3)
    print("- 47: White\n")
    time.sleep(0.3)

    print(f"{bold('Text Styles')}")
    time.sleep(0.3)
    print("- 0: Reset / Normal")
    time.sleep(0.3)
    print("- 1: Bold")
    time.sleep(0.3)
    print("- 2: Dim / Faint")
    time.sleep(0.3)
    print("- 3: Italic (not always supported)")
    time.sleep(0.3)
    print("- 4: Underline")
    time.sleep(0.3)
    print("- 5: Blink Slow")
    time.sleep(0.3)
    print("- 6: Blink Rapid (rarely supported)")
    time.sleep(0.3)
    print("- 7: Inverse / Reverse")
    time.sleep(0.3)
    print("- 8: Hidden / Conceal")
    time.sleep(0.3)
    print("- 9: Strikethrough\n")
    time.sleep(0.3)

    print(f"{bold('Example 1: Combining Codes')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("print('\\033[1;32mBold Green Text\\033[0m')")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Bold Green Text (students format themselves)\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use '\\033[<style>;<foreground>;<background>mText\\033[0m' for custom formatting.")
    time.sleep(0.3)
    print("- Reset code '\\033[0m' clears previous styles to avoid affecting other outputs.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Simple Time
def time_sleep():
    print(f"\n========== {bold(bright_yellow('TIME / SLEEP'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Learn how to control the pacing of your program using time.sleep().")
    time.sleep(0.3)
    print("- This pauses execution for a number of seconds.\n")
    time.sleep(0.3)

    print(f"{bold('Example 1: Simple Pause')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("import time")
    time.sleep(0.3)
    print("print('Hello')")
    time.sleep(0.3)
    print("time.sleep(2)")
    time.sleep(0.3)
    print("print('World!')")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Hello")
    time.sleep(2)
    print("World!\n")
    time.sleep(0.3)

    print(f"{bold('Example 2: Multiple Delays')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("for i in range(3):")
    time.sleep(0.3)
    print("    print(i)")
    time.sleep(0.3)
    print("    time.sleep(1)")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("0")
    time.sleep(1)
    print("1")
    time.sleep(1)
    print("2\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- time.sleep(seconds) pauses the program for the specified number of seconds.")
    time.sleep(0.3)
    print("- Useful for creating delays, pacing outputs, or animations in the console.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Execute
def execs():
    print(f"\n========== {bold(bright_cyan('EXEC'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Learn how to execute a string of Python code dynamically using exec().")
    time.sleep(0.3)
    print("- Useful for practice sandboxes or running code stored as strings.\n")
    time.sleep(0.3)

    print(f"{bold('Example 1: Simple Execution')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("code = \"print('Hello from exec!')\"")
    time.sleep(0.3)
    print("exec(code)")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Hello from exec!\n")
    time.sleep(0.3)

    print(f"{bold('Example 2: Multiple Lines')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("code = '''")
    time.sleep(0.3)
    print("for i in range(3):")
    time.sleep(0.3)
    print("    print(i)")
    time.sleep(0.3)
    print("'''")
    time.sleep(0.3)
    print("exec(code)")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("0\n1\n2\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- exec(string) runs the Python code inside the string as if it were normal code.")
    time.sleep(0.3)
    print("- Be careful when executing code from user input due to security risks.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Try
def try_lesson():
    print(f"\n========== {bold(bright_green('TRY'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Learn how to use try blocks to attempt code execution that might fail.")
    time.sleep(0.3)
    print("- No except is taught here; this shows the structure of try alone.\n")
    time.sleep(0.3)

    print(f"{bold('Example 1: Attempt Division')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("try:")
    time.sleep(0.3)
    print("    x = int(input('Enter a number: '))")
    time.sleep(0.3)
    print("    print(10 / x)")
    time.sleep(0.3)
    print("# No except used here")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("User enters 2 → 5.0")
    time.sleep(0.3)
    print("User enters 0 → program stops at this point (no except used)\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Wrap code that might fail inside a try: block.")
    time.sleep(0.3)
    print("- Without except, errors will stop the program, but try illustrates the structure.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Strings
def strings():
    print(f"\n========== {bold(bright_cyan('STRING METHODS'))} ==========")
    time.sleep(0.3)
    print("Instructions:")
    time.sleep(0.3)
    print("- Learn how to manipulate strings using common methods.")
    time.sleep(0.3)
    print("- Methods covered: .strip(), .lower(), .upper()\n")
    time.sleep(0.3)

    print(f"{bold('Example 1: .strip()')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("text = '   Hello World   '")
    time.sleep(0.3)
    print("print(text.strip())")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("Hello World\n")
    time.sleep(0.3)

    print(f"{bold('Example 2: .lower()')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("text = 'Python'")
    time.sleep(0.3)
    print("print(text.lower())")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("python\n")
    time.sleep(0.3)

    print(f"{bold('Example 3: .upper()')}")
    time.sleep(0.3)
    print("INPUT:")
    time.sleep(0.3)
    print("text = 'python'")
    time.sleep(0.3)
    print("print(text.upper())")
    time.sleep(0.3)
    print("\nOUTPUT:")
    time.sleep(0.3)
    print("PYTHON\n")
    time.sleep(0.3)

    input(green('Press Enter to see Hint...'))
    time.sleep(0.3)
    print("\nHint:")
    time.sleep(0.3)
    print("- Use .strip() to remove leading/trailing spaces from strings.")
    time.sleep(0.3)
    print("- Use .lower() to convert text to lowercase.")
    time.sleep(0.3)
    print("- Use .upper() to convert text to uppercase.\n")
    time.sleep(0.3)
    input(green('Press Enter to return.'))

# Easy 
def guess_easy():
    os.system('cls')
    print(f"\n========== {bold(bright_magenta('GUESS THE OUTPUT - EASY'))} ==========")
    time.sleep(0.3)

    # Question 1
    print("Q1: What is the output of print(2 + 3 * 4)?")
    time.sleep(0.3)
    print(f"{red('1')}. 14")
    print(f"{red('2')}. 20")
    print(f"{red('3')}. 24")
    print(f"{red('4')}. 9")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '1':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: 14"))
    time.sleep(1.5)

    # Question 2
    print("\nQ2: What is the output of print('Hello' + 'World')?")
    time.sleep(0.3)
    print(f"{red('1')}. Hello World")
    print(f"{red('2')}. HelloWorld")
    print(f"{red('3')}. Hello+World")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '2':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: HelloWorld"))
    time.sleep(1.5)

    # Question 3
    print("\nQ3: What is the output of print(len('Python'))?")
    time.sleep(0.3)
    print(f"{red('1')}. 5")
    print(f"{red('2')}. 6")
    print(f"{red('3')}. 7")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '2':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: 6"))
    time.sleep(1.5)

    # Question 4
    print("\nQ4: What is the output of print('Python'.upper())?")
    time.sleep(0.3)
    print(f"{red('1')}. python")
    print(f"{red('2')}. Python")
    print(f"{red('3')}. PYTHON")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '3':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: PYTHON"))
    time.sleep(1.5)

    # Question 5
    print("\nQ5: What is the output of print(10 // 3)?")
    time.sleep(0.3)
    print(f"{red('1')}. 3")
    print(f"{red('2')}. 3.33")
    print(f"{red('3')}. 4")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '1':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: 3"))
    time.sleep(1.5)

    input(green("\nPress Enter to return to Guess the Output menu..."))

# Medium
def guess_medium():
    os.system('cls')
    print(f"\n========== {bold(bright_yellow('GUESS THE OUTPUT - MEDIUM'))} ==========")
    time.sleep(0.3)

    # Question 1
    print("Q1: What is the output of print(5 % 2)?")
    time.sleep(0.3)
    print(f"{red('1')}. 0")
    print(f"{red('2')}. 1")
    print(f"{red('3')}. 2")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '2':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: 1"))
    time.sleep(1.5)

    # Question 2
    print("\nQ2: What is the output of print('Python'[1:4])?")
    time.sleep(0.3)
    print(f"{red('1')}. Pyt")
    print(f"{red('2')}. yth")
    print(f"{red('3')}. ytho")
    print(f"{red('4')}. ythn")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '2':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: yth"))
    time.sleep(1.5)

    # Question 3
    print("\nQ3: What is the output of print(bool(0))?")
    time.sleep(0.3)
    print(f"{red('1')}. True")
    print(f"{red('2')}. False")
    print(f"{red('3')}. 0")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '2':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: False"))
    time.sleep(1.5)

    # Question 4
    print("\nQ4: What is the output of print(list(range(3)))?")
    time.sleep(0.3)
    print(f"{red('1')}. [0, 1, 2]")
    print(f"{red('2')}. [1, 2, 3]")
    print(f"{red('3')}. [0, 1, 2, 3]")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '1':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: [0, 1, 2]"))
    time.sleep(1.5)

    # Question 5
    print("\nQ5: What is the output of print(3 ** 2)?")
    time.sleep(0.3)
    print(f"{red('1')}. 5")
    print(f"{red('2')}. 6")
    print(f"{red('3')}. 9")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '3':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: 9"))
    time.sleep(1.5)

    input(green("\nPress Enter to return to Guess the Output menu..."))

# Hard
def guess_hard():
    os.system('cls')
    print(f"\n========== {bold(bright_red('GUESS THE OUTPUT - HARD'))} ==========")
    time.sleep(0.3)

    # Question 1
    print("Q1: What is the output of print(2 ** 3 ** 2)?")
    time.sleep(0.3)
    print(f"{red('1')}. 64")
    print(f"{red('2')}. 512")
    print(f"{red('3')}. 256")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '2':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: 512"))
    time.sleep(1.5)

    # Question 2
    print("\nQ2: What is the output of print(list('Python')[::-1])?")
    time.sleep(0.3)
    print(f"{red('1')}. ['n', 'o', 'h', 't', 'y', 'P']")
    print(f"{red('2')}. ['P', 'y', 't', 'h', 'o', 'n']")
    print(f"{red('3')}. ['P', 'y', 't', 'h', 'o']")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '1':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: ['n', 'o', 'h', 't', 'y', 'P']"))
    time.sleep(1.5)

    # Question 3
    print("\nQ3: What is the output of print(bool([]) or True)?")
    time.sleep(0.3)
    print(f"{red('1')}. True")
    print(f"{red('2')}. False")
    print(f"{red('3')}. []")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '1':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: True"))
    time.sleep(1.5)

    # Question 4
    print("\nQ4: What is the output of print('Python'[-1::-2])?")
    time.sleep(0.3)
    print(f"{red('1')}. 'yhn'")
    print(f"{red('2')}. 'noth'")
    print(f"{red('3')}. 'nhy'")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '3':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: nhy"))
    time.sleep(1.5)

    # Question 5
    print("\nQ5: What is the output of print((lambda x: x*2)(5))?")
    time.sleep(0.3)
    print(f"{red('1')}. 5")
    print(f"{red('2')}. 10")
    print(f"{red('3')}. 25")
    print(f"{red('4')}. Error")
    choice = input(green("Your answer (1-4): ")).strip()
    if choice == '2':
        print(cyan("Correct!"))
    else:
        print(red("Wrong! Correct answer: 10"))
    time.sleep(1.5)

    input(green("\nPress Enter to return to Guess the Output menu..."))
